Repository Caffeinated-Typists/PyWeek-34, pull requests merged in 2022-09, with the labels that each got.

#12 Create char
  PyWeek-34/__main__.py
  PyWeek-34/characters/protagonist.py
Labels: enhancement

#18 Added animations to inbuilt Sprite
  PyWeek-34/__main__.py
  PyWeek-34/characters/protagonist.py
Labels: enhancement

#20 Infinite map movement, with proper character position
  PyWeek-34/__main__.py
  PyWeek-34/characters/protagonist.py
Labels: enhancement

#35 changed file names and fixed shooting animation bugs
  PyWeek-34/characters/jetpack character/no_weapon_white_helmet_flying.png
  PyWeek-34/characters/jetpack character/no_weapon_white_helmet_flying_die.png
  PyWeek-34/characters/jetpack character/no_weapon_white_helmet_standing_die.png
  PyWeek-34/characters/jetpack character/no_weapon_white_helmet_standing_idle.png
  PyWeek-34/characters/jetpack character/no_weapon_white_helmet_standing_run.png
  PyWeek-34/characters/jetpack character/no_weapon_white_helmet_standing_walk.png
  PyWeek-34/characters/jetpack character/with_weapon_flying.png
  PyWeek-34/characters/jetpack character/with_weapon_flying_die.png
  PyWeek-34/characters/jetpack character/with_weapon_flying_shoot.png
  PyWeek-34/characters/jetpack character/with_weapon_standing_idle.png
  PyWeek-34/characters/jetpack character/with_weapon_standing_shoot.png
  PyWeek-34/characters/protagonist.py
Labels: bug

#42 bug:Fixed bug where character would drop on pressing shoot
  PyWeek-34/__main__.py
Labels: bug

#47 improved title screen
  PyWeek-34/__main__.py
  PyWeek-34/resources/Game Assets/GROBOLD.ttf
Labels: enhancement

#59 Create enemies
  Project-Aries/__main__.py
  Project-Aries/characters/UFO Sprites/laser_burst_0.png
  Project-Aries/characters/UFO Sprites/laser_burst_1.png
  Project-Aries/characters/UFO Sprites/laser_burst_2.png
  Project-Aries/characters/UFO Sprites/laser_burst_3.png
  Project-Aries/characters/UFO Sprites/laser_burst_4.png
  Project-Aries/characters/UFO Sprites/ship_0.png
  Project-Aries/characters/UFO Sprites/ship_1.png
  Project-Aries/characters/UFO Sprites/ship_2.png
  Project-Aries/characters/UFO Sprites/ship_3.png
  Project-Aries/characters/UFO Sprites/ship_4.png
  Project-Aries/characters/UFO Sprites/ship_damage_0.png
  Project-Aries/characters/UFO Sprites/ship_damage_1.png
  Project-Aries/characters/UFO Sprites/ship_damage_2.png
  Project-Aries/characters/UFO Sprites/ship_damage_3.png
  Project-Aries/characters/UFO Sprites/ship_damage_4.png
  Project-Aries/characters/UFO Sprites/ufo1.png
  Project-Aries/characters/UFO Sprites/ufo2.png
  Project-Aries/characters/UFO Sprites/ufo3.png
  Project-Aries/characters/UFO Sprites/ufo4.png
  Project-Aries/characters/crawler.py
  Project-Aries/characters/enemy.py
  Project-Aries/characters/protagonist.py
  Project-Aries/characters/spaceship.py
  Project-Aries/characters/ufo.py
Labels: enhancement

#60 Added sounds to the game
  Project-Aries/__main__.py
  Project-Aries/characters/UFO Sprites/Bullet Impact 21.wav
  Project-Aries/characters/jetpack character/sounds/ending.ogg
  Project-Aries/characters/jetpack character/sounds/main.ogg
  Project-Aries/characters/jetpack character/sounds/pew.wav
  Project-Aries/characters/jetpack character/sounds/start.ogg
  Project-Aries/characters/jetpack character/sounds/steps_platform.ogg
  Project-Aries/characters/protagonist.py
  Project-Aries/resources/Game Assets/Sounds/background-loop-melodic-techno.mp3
Labels: enhancement

#62 Update README.md
  README.md
Labels: documentation

#66 added restart UI elements
  Project-Aries/__main__.py
  Project-Aries/characters/enemy.py
  Project-Aries/characters/protagonist.py
Labels: enhancement

#69 Added Score Functionality
  Project-Aries/__main__.py
  Project-Aries/characters/ufo.py
Labels: enhancement

#72 fix: Death animation and crawler bugs
  Project-Aries/__main__.py
  Project-Aries/characters/protagonist.py
Labels: bug

#76 Added Functionality for spaceship
  Project-Aries/__main__.py
  Project-Aries/characters/Spaceship/Ship1.png
  Project-Aries/characters/Spaceship/Ship2.png
  Project-Aries/characters/Spaceship/Ship3.png
  Project-Aries/characters/Spaceship/Ship4.png
  Project-Aries/characters/Spaceship/Ship5.png
  Project-Aries/characters/Spaceship/Ship_damage1.png
  Project-Aries/characters/Spaceship/Ship_damage2.png
  Project-Aries/characters/Spaceship/Ship_damage3.png
  Project-Aries/characters/Spaceship/laser.png
  Project-Aries/characters/spaceship.py
Labels: enhancement
